name: Run Tests

on:
  pull_request:
    branches:

  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 14.17
      
      - name: Install Packages
        run: yarn

      - name: Run Tests
        run: yarn test